### ISSUE TITLE
Application for live data monitoring on Windows 

### ISSUE THREAD

**Issue by falfaroc** [normaldotcom/canable-fw#12]
After setting up the `canable` with the `slcan` firmware, I am trying to find a reliable application to monitor CAN traffic on Windows. `canable.io` suggests using `canact-app` but after setting it up, there is no traffic appearing even though I have verified that data is being sent through.

Is there any other Windows application to monitor data for this firmware?

**Comment by normaldotcom** [comment]
This is an old issue but I wanted to update: the cangaroo application now detects and can send/receive packets with a CANable running slcan firmware. [https://canable.io/getting-started.html#cangaroo](https://canable.io/getting-started.html#cangaroo)
