### ISSUE TITLE
PCAN emulator hangs after several minutes

### ISSUE THREAD

**Issue by Kabron287** [normaldotcom/canable-fw#13]
Hello, 
there is PCAN emulator FW on the updater page of canable.io.

Testing it with canable pro and PCAN-view (sending packets every second) I found that it stops work after 15-20 minutes and only power cycle restore operation.

Is it possible to obtain the source code?

**Comment by normaldotcom** [comment]
Closing as unrelated to this repo--I would recommend creating an issue here: https://github.com/moonglow/pcan_cantact
